# Site settings
title: Lessonly Technology Blog
email: your-email@domain.com
description: >
  Product and engineering at Lessonly
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lessonly.github.io" # the base hostname & protocol for your site
twitter_username: lessonly
github_username: lessonly
collections:
  open_source:
    output: false
  styleguide:
    output: true
    permalink: /styleguide/:path/

# Build settings
kramdown:
  input: GFM

paginate: 5
permalink: /:title/

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
